name: what_to_do
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  action_slider: ^0.6.1
  metaballs: ^1.5.0
  simple_circular_progress_bar: ^1.0.2
  google_fonts: ^4.0.3
  animated_text_kit: ^4.2.2
  sqflite: ^2.2.6
  random_avatar: ^0.0.8
  social_share: ^2.3.1
  screenshot: ^1.3.0
  path_provider: ^2.0.14
  font_awesome_flutter: ^10.4.0
  adaptive_theme: ^3.2.0
  shared_preferences: ^2.1.0
  introduction_screen: ^3.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
